comments:
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false

style:
  MagicNumber:
    active: false
  ReturnCount:
    active: false
